### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by atageldi194229** [atageldi194229/pinging_app#1]
- [x] show address location from api
- [x] show address ping time in ms
- [ ] add backround proccess for fetching unique addresses and collecting after every 10 minutes
- [x] maybe upgrade ui
